### ISSUE TITLE
the horizontal line in the fraction on the tool bar isn't quite level

### ISSUE THREAD

**Issue by jbphet** [phetsims/graphing-lines#59] opened 2016-01-15 18:04 UTC
I noticed this when looking around at the math fonts that we've used in the past.  On the current master version of Graphing Lines, and also in the currently published version (v1.1.0), the little separator line on one of the fractions isn't quite level.  Here is a screenshot:

![graphing-lines-non-level-line](https://cloud.githubusercontent.com/assets/3082831/12360866/b57d2858-bb77-11e5-908f-c5ce9a5881d1.PNG)

**Comment by pixelzoom** [comment] 2016-01-15 18:15
Browser and OS?

**Comment by ariel-phet** [comment] 2016-01-15 18:17
I am seeing this issue on Chrome, FF, and IE11 on Win 7

**Comment by pixelzoom** [comment] 2016-01-15 18:18
Reproduced on Mac OS 10.11.2 with Chrome latest.  The horizontal lines in the interactive version of this equation also look off:

![screenshot_108](https://cloud.githubusercontent.com/assets/3046552/12361142/a2fc00bc-bb79-11e5-90aa-fcc7e90b8d8e.png)

**Comment by ariel-phet** [comment] 2016-01-15 18:18
yes, but oddly, only on the slope screen

**Comment by ariel-phet** [comment] 2016-01-15 18:19
Notice crisp on slope-intercept screen

![capture](https://cloud.githubusercontent.com/assets/4051174/12361171/d0d92dc0-bb79-11e5-9f57-c53843a33a11.PNG)

**Comment by pixelzoom** [comment] 2016-01-15 18:21
It's a bug specific to the Slope screen, identified and trivial to fix. Fix will be pushed in a few minutes.

**Comment by pixelzoom** [comment] 2016-01-15 18:28
Fixed and pushed to master and 1.1 branches.  Assigned to @jbphet to verify in master.

I see no reason to publish a maintenance release for this. @ariel-phet do you agree?

**Comment by pixelzoom** [comment] 2016-01-15 18:28
Screenshot showing the fix:

![screenshot_109](https://cloud.githubusercontent.com/assets/3046552/12361400/1fae7972-bb7b-11e5-9024-c9c6f158df61.png)

**Comment by ariel-phet** [comment] 2016-01-15 18:42
@pixelzoom - why opposed to a maintenance release? I know it is minor, but it seems a little distasteful, and we probably won't be doing a true republish of this sim for awhile?

**Comment by pixelzoom** [comment] 2016-01-15 18:47
BLL 1.3.1 maintenance release took me ~2 hours due to incompatibility between chipper and build-server. That issue is not resolved, and applies to maintenance releases of this simulation.  So a maintenance release will require either (a) addressing the build issue or (b) doing a manual build and deploy of all translations.  If that's how you want me to spend my time, let me know.  Doesn't seem worth the expense to me.

**Comment by ariel-phet** [comment] 2016-01-15 18:49
@pixelzoom indeed...can we plan a maintenance release once that issue is addressed? (my be a nice test if we are confident in the fix)

**Comment by pixelzoom** [comment] 2016-01-15 18:52
Btw... I agree that it's a little distasteful, and I don't like having bugs in things that I'm responsible for. But (specifically) this issue has been present in the sim from day 1, and has never been reported. And (in general) publishing a maintenance release for trivial things like this is not something that most software organizations would do. Unless the product is clearly broken, you typically want to batch your fixes and publish occasional maintenance releases.  So regardless of when the build process is fixed, this issue doesn't seem to have the priority that warrants a maintenance release.  My recommendation is to live with it - we'll be doing another release for something significant before you know it.  That said... you're driving the bus, so your call.

**Comment by pixelzoom** [comment] 2016-01-15 18:54
I agree that it's a little distasteful, and I don't like having flaws in things that I'm responsible for. But (specifically) this issue has been present in the sim from day 1, has never been reported, and has no effect on the ability to use the sim or its correctness. And (in general) publishing a maintenance release for trivial things like this is not something that most software organizations would do. Unless the product is clearly broken, you typically want to batch your fixes and publish occasional maintenance releases.  So regardless of when the build process is fixed, this issue doesn't seem to have the priority that warrants a maintenance release.  My recommendation is to live with it - we'll be doing another release for something significant before you know it.  That said... you're driving the bus, so your call.

**Comment by pixelzoom** [comment] 2016-01-15 18:57
Btw... If we're going to do a maintenance release for things like this, that demotivates me to fix issues like this immediately.  It would take me much less time to wait until I have a significant number of issues reported, and triage/fix them when we need to redeploy the sim for something significant.

**Comment by ariel-phet** [comment] 2016-01-15 18:59
Sure, removing assignee, can wait until redepoloy

**Comment by pixelzoom** [comment] 2016-01-15 19:08
Would still like to have @jbphet verify, so restoring assignee.

**Comment by jbphet** [comment] 2016-01-15 20:36
Changes look good, and I verified the behavior by loading the fixed version and flipping back and forth between it and the published version.  Definitely appears fixed.  Based on the discussion above, I'll leave this issue open but unassigned.

**Comment by pixelzoom** [comment] 2016-01-21 19:09
Labeling this as 'QA' so that it gets regression tested before publication.

**Comment by pixelzoom** [comment] 2016-02-29 18:15
This was published without verification in 1.1.1 when https://github.com/phetsims/yotta/issues/17 (Hewlett Google Analytics) was addressed.  I verified that this looks good in the latest version (1.1.2) that is on the PhET website.

Closing.

**Closed by pixelzoom** 2016-02-29 18:15 UTC
Labels: status:fixed-pending-testing
