### ISSUE TITLE
Estimate for a "slope-intercept only" version

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/graphing-lines#66] opened 2017-02-17 19:06 UTC
@pixelzoom I was asked yesterday by @kathy-phet to see what it would take to make a version of graphing lines that only included slope-intercept. Obviously publishing a version that removed the point-slope screen is not too challenging, but because the game mixes and matches various types of challenges, it was our impression that disentangling point-slope challenges from the game might be fairly intensive.

(It was also @kathy-phet recollection that you might have warned us at the time of the game creation that it would be difficult to disentangle if we ever wanted to do the above)

Could you give a rough estimate of hours for creating a version of this sim that includes the slope-intercept screen (potentially the slope screen as well) but removes all point-slope challenges from the game and replaces them with slope-intercept challenges?

@kathy-phet felt that for the math grant this could count as a separate sim, so this question would come higher priority than the question of Molecule Polarity.

**Comment by pixelzoom** [comment] 2017-02-17 19:14
@ariel-phet Please clarify what is desired here. Do you simply want a separate sim that has only the existing "Slope-Intercept" screen from the Graphing Lines sim? Or are there other changes?

**Comment by ariel-phet** [comment] 2017-02-17 19:15
@pixelzoom see above, sorry things got a little whacky when I created the issue. Happy to discuss over skype as well

**Comment by pixelzoom** [comment] 2017-02-17 19:37
Discussed with @ariel-phet on Skype. Would like an estimate sometime next week.

**Comment by pixelzoom** [comment] 2017-02-17 19:40
Development tasks include:

• set up new repository (graphing-slope-intercept? slope-intercept?)
• cherry pick screens from graphing-lines
• modify ChallengeFactory*.js (6 files, 1 for each level)

Design tasks:
• come up with additional sets of challenges to "choose 1" from

Testing tasks:
• regression test new sim
• regression test graphing-lines

**Comment by pixelzoom** [comment] 2017-02-23 21:12
Co-assigning to @amanda-phet to come up with a name for this sim, so that I can create the corresponding repository.

**Comment by pixelzoom** [comment] 2017-03-02 20:17
Specification of the challenges for each game level is complicated, and the Java design document looks like it might be stale (not in-sync with the implementation).  I sent @amanda-phet a link to the code in GitHub repository:

> Javascript code for Graphing Lines “challenge factories” are here:
https://github.com/phetsims/graphing-lines/tree/master/js/linegame/model
The files of interest are ChallengeFactory1.js through ChallengeFactory6.js,  where the number corresponds to the game level.

**Comment by pixelzoom** [comment] 2017-03-02 20:18
Rather than complicate the ChallengeFactory*.js files with `if-then-else` logic, we should consider having a separate set of such factories for this new sim, even if that means some duplication of code.

**Comment by pixelzoom** [comment] 2017-03-03 14:35
Estimate for my time is 36 hours, with this breakdown:

• 2 hr - Set up new repository and basic sim skeleton with Slope, Point-Slope and Game screens.
• 3 hr - Assist with completing a specification of the challenges for each game level.
• 2 hr - Based on the specification, investigate whether to modify the existing challenge factories, or create new challenge factories. Choose the approach that is least complicated and most maintainable.
• 15 hr - Modify existing challenge factories, or write new challenge factories.
• 5 hr - Modify the existing "Game" screen to either (a) configure the existing challenge factories to exclude point-slope, or (b) use the new set of challenge factories.
• 4 hr - change requests
• 5 hr - support during RC testing and publishing

Assumptions:

• @amanda-phet will lead creation of the specification. I'll assist with information about how the current game works. The game can be specified as deltas to the current game, or it can be an entirely new specification (your choice). Google doc is preferred, so that we have documentation for posterity.
• There are no new challenge types. All of the challenge types requires are currently implemented in Graphing Lines, and will not require significant modification.
• There are no changes required to the Slope and Slope-Intercept screens.

Next steps:

• choose a name for the sim & repository 
• create the game specification

Assigning to @ariel-phet and @amanda-phet to review my estimate.

**Comment by ariel-phet** [comment] 2017-03-03 17:27
@pixelzoom that estimate all seems quite reasonable, along with the assumptions. Considering this estimate and @amanda-phet priorities as discussed at the meeting, this should probably be your next priority after unit rates. 

I will leave it to @amanda-phet to figure out a name for the sim, happy to help on the game specification.

**Comment by pixelzoom** [comment] 2017-03-07 17:13
Unit Rates is now in testing.  So I'd like to make a sprint on this sometime in the next few days.  But I'll need to create a repository to do so, which requires choosing a sim name.  We can change the sim name later, but not at zero cost (repository needs to be move, code needs to be changed, all developers need to change their working copy,...) 

Some possible names:

Graphing Slope-Intercept Lines
Graphing Lines: Slope-Intercept
Slope-Intercept Form
Slope-Intercept Lines

@amanda-phet What sim name do you want me to use?

**Comment by pixelzoom** [comment] 2017-03-07 19:32
Skype call with @amanda-phet and @ariel-phet: 

We'll go with graphing-slope-intercept.  I'll create an issue in that new repository to finalize the name.

**Comment by pixelzoom** [comment] 2017-03-07 21:20
Moving further work and discussion to the graphing-slope-intercept repository. 

Closing.

**Closed by pixelzoom** 2017-03-07 21:20 UTC
Labels: priority:2-high
