### ISSUE TITLE
Control points lose center filling in Put Points on Line

### ISSUE THREAD

**Issue by ayeemdee** [phetsims/graphing-lines#82] opened 2017-06-06 23:05 UTC
The problem is most easily replicated by arranging the points in a horizontal line or moving them close to each other.
I'm only getting this problem on an iPad 2 in portrait. It doesn't reproduce in landscape or on iPad Air 2 or Galaxy S6. Therefore it might just be related to the poor resolution of the iPad 2.

This bug is seen both in Graphing Slope Intercept and Graphing Lines (published version). 

1. Play Line Game Level 3 or 4
2. Get to 'Put Points on Line" game type
3. Move Control Points around into a horizontal line or close to each other
4. Control points lose some or all of their center filling and sometimes only an outline is left

![img_0087](https://user-images.githubusercontent.com/2342849/26854863-495897f4-4ad5-11e7-99f9-7a975b72158d.PNG)

Additionally I realize that we generally don't concern ourselves with reporting bugs in portrait mode but thought it should be reported anyways.

For phetsims/tasks/issues/852. Seen on iPad 2 iOS 9.3.5. Assigning to @ariel-phet to defer or delegate time to fix.

Troubleshooting information (do not edit):
Name: ‪Graphing Slope-Intercept‬
URL: http://www.colorado.edu/physics/phet/dev/html/graphing-slope-intercept/1.0.0-rc.2/graphing-slope-intercept_en.html
Version: 1.0.0-rc.2 2017-06-05 19:51:54 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1
Language: en-us
Window: 980x1183
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-124.1)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"5c3f9204","branch":"HEAD"},"axon":{"sha":"f475e68c","branch":"HEAD"},"babel":{"sha":"be718c9a","branch":"master"},"brand":{"sha":"f4b72cac","branch":"HEAD"},"chipper":{"sha":"3061f107","branch":"HEAD"},"dot":{"sha":"57936fff","branch":"HEAD"},"graphing-lines":{"sha":"2f4ba063","branch":"HEAD"},"graphing-slope-intercept":{"sha":"15490d45","branch":"HEAD"},"joist":{"sha":"06775098","branch":"HEAD"},"kite":{"sha":"0cc5b620","branch":"HEAD"},"phet-core":{"sha":"76ec0204","branch":"HEAD"},"phetcommon":{"sha":"d0ffe176","branch":"HEAD"},"query-string-machine":{"sha":"e7055778","branch":"HEAD"},"scenery":{"sha":"d1d2ca2d","branch":"HEAD"},"scenery-phet":{"sha":"6dc1a064","branch":"HEAD"},"sherpa":{"sha":"0e326d54","branch":"HEAD"},"sun":{"sha":"3967c777","branch":"HEAD"},"tandem":{"sha":"30603e66","branch":"HEAD"},"vegas":{"sha":"6bd734e2","branch":"HEAD"},"vibe":{"sha":"5e8151e1","branch":"HEAD"}}

**Comment by pixelzoom** [comment] 2017-06-07 15:46
Wow, that's weird. I have no idea why points would fail to fully redraw. @jonathanolson do you have any ideas?

**Comment by pixelzoom** [comment] 2017-06-07 15:47
The points are implemented in graphing-lines.PlottedPointNode, a subtype of scenery-phet.ShadedSphereNode.

**Comment by pixelzoom** [comment] 2017-06-07 18:58
@ayeemdee said:
> I'm only getting this problem on an iPad 2 in portrait

Does that mean that you've been unable to reproduce on all other platforms?  Or does it mean that you noticed it on iPad2, but only in portrait? 

Can you please report on iPad2 in portrait with Chrome?   And a couple of desktop platforms, including Safari?

**Comment by phet-steele** [comment] 2017-06-07 21:23
@pixelzoom this happens in iPad2 Chrome (this is expected, see https://github.com/phetsims/special-ops/issues/57#issuecomment-274154299) and certainly seems related to iPad 2 (iOS 9.3.5 on an iPad Air 2 showed no issue). Similarly, not seeing issues on desktop platforms (macOS 10.12.5 Safari, Win 10 Chrome).

**Comment by ariel-phet** [comment] 2017-06-07 21:34
Considering the low percentages here (iPad2 is shrinking usage, portrait is less likely) and the fact that this bug exists in the published version and has gone seemingly unnoticed, I am going to mark won't fix.

**Comment by phet-steele** [comment] 2017-06-07 21:45
> this bug exists in the published version

@pixelzoom before you ask, this was checked as far back as 1.0.0 and the bug still exists. Not introduced in the published version from a couple days ago (1.2.0).

**Comment by pixelzoom** [comment] 2017-06-07 22:13
So to summarize:
• specific to iPad2 in portrait mode
• occurs across browsers (Safari, Chrome)
• certainly not a sim-specific issue, would need to be addressed in scenery
• will not fix, per @ariel-phet 

@jonathanolson Do you want to create a low-priority scenery issue?

**Comment by jonathanolson** [comment] 2017-06-07 22:17
Created https://github.com/phetsims/scenery/issues/623 to track permanently as its own browser-specific issue.

**Closed** 2017-06-07 22:21 UTC
Labels: type:bug, type:wontfix
