### ISSUE TITLE
Slope writing is inconsistent size

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-lines#114] opened 2019-02-04 22:30 UTC
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/277
The words "Slope is ___" on the Slope screen are smaller on the active line then the saved lines.  This is most noticeable when you hit save line and the two overlap.  Does not occur on published version.
**Steps to reproduce:**
1. Set stringTest=double
2. Go to slope screen
3. Hit save line button

**Screenshots:**
![funky](https://user-images.githubusercontent.com/41024075/52241665-94016880-2891-11e9-9f75-2b09d21c0176.jpg)
![activeissmall](https://user-images.githubusercontent.com/41024075/52241672-96fc5900-2891-11e9-9c06-8b1f9087d6ff.jpg)

Troubleshooting information (do not edit):

<details>

Name: ‪Graphing Lines‬:‪Graphing Lines‬
URL: https://phet-dev.colorado.edu/html/graphing-lines/1.3.0-rc.1/phet/graphing-lines_en_phet.html?stringTest=double
Version: 1.3.0-rc.1 2019-01-31 19:26:59 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36
Language: en-US
Window: 1536x731
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment] 2019-02-04 22:32
They probably have different `maxWidth` values.

**Comment by pixelzoom** [comment] 2019-02-04 22:36
Hmmm... When the sim is first started, the sizes the same, see screenshot below.  Then after playing with the sim for awhile, the equation on interactive line becomes smaller.  Are you seeing this too @KatieWoe?

<img width="904" alt="screenshot_1019" src="https://user-images.githubusercontent.com/3046552/52241973-7b458280-2892-11e9-8f66-8cd24e3d29aa.png">

**Comment by KatieWoe** [comment] 2019-02-04 22:37
Yes.  Now that I refresh, I do.

**Comment by pixelzoom** [comment] 2019-02-04 22:38
It looks like making a vertical line ("Slope is undefined") is the action that makes the interactive line's label reduce its size.

**Comment by KatieWoe** [comment] 2019-02-04 22:40
Looks like.  And now that you mention it, something similar happens at that spot on the other two screens as well, but mostly noticeable when at the undefined spot.

**Comment by KatieWoe** [comment] 2019-02-04 22:41
And in https://github.com/phetsims/QA/issues/278, now that I know more what to look for

**Comment by pixelzoom** [comment] 2019-02-05 03:51
@KatieWoe please verify in master. If it looks OK, then leave this issue open for regression testing in next RC.

**Comment by KatieWoe** [comment] 2019-02-05 16:17
looks good in master

**Comment by KatieWoe** [comment] 2019-02-12 22:48
Confirmed in both rcs

**Comment by KatieWoe** [comment] 2019-02-13 16:32
This error seems to be back in https://github.com/phetsims/QA/issues/286 and https://github.com/phetsims/QA/issues/287.
![regress](https://user-images.githubusercontent.com/41024075/52727352-41e7d380-2f72-11e9-8f74-4ebd19df968b.jpg)

**Comment by pixelzoom** [comment] 2019-02-13 16:57
Bummer. #114 and #117 are intertwined.  When I made the recent change for #117 (see https://github.com/phetsims/graphing-lines/issues/117#issuecomment-462989759), I did test #114, but apparently not well enough.

**Comment by pixelzoom** [comment] 2019-02-18 22:22
@KatieWoe please verify this in master.  Check with #117, since they are related.

**Comment by KatieWoe** [comment] 2019-02-18 22:58
Doesn't happen in the first screens, but still happens on game screens. @pixelzoom

**Comment by pixelzoom** [comment] 2019-02-18 23:12
@KatieWoe please elaborate, I don't understand.  Lines in the games are not labeled with equations, so how can this issue be relevant to the game screens?

**Comment by KatieWoe** [comment] 2019-02-18 23:16
See explanation https://github.com/phetsims/graphing-lines/issues/117#issuecomment-464918785

**Comment by pixelzoom** [comment] 2019-02-18 23:20
OK, thanks.  So there's nothing wrong with the size of equations used to label lines on the graph, correct?

**Comment by KatieWoe** [comment] 2019-02-18 23:21
Didn't seem like it

**Comment by pixelzoom** [comment] 2019-02-19 00:40
Pending regression testing in 1.3.0-rc.4.

**Comment by KatieWoe** [comment] 2019-02-19 16:38
I did have a quick question for GL though.  I noticed that "not a line" change size depending on what happened before it.  I think this was known (https://github.com/phetsims/graphing-lines/issues/117#issuecomment-460484858) but I wanted to make sure before I oked the issue.
![differentsizes](https://user-images.githubusercontent.com/41024075/53031467-283f0400-342a-11e9-8f88-14d292315759.gif)

**Comment by pixelzoom** [comment] 2019-02-19 16:41
Thanks @KatieWoe.  What you're showing above is relevant only to #117, not this issue.   Displaying "is not a line" is handled separately from equations.  

So if you don't find anything else, feel free to close this issue.

**Closed** 2019-02-19 16:42 UTC
Labels: status:fixed-pending-testing, type:i18n
