### ISSUE TITLE
Firefox anti-aliasing allows obscured lines and equations to be seen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-lines#125] opened 2019-02-13 22:15 UTC
For https://github.com/phetsims/QA/issues/287 and https://github.com/phetsims/QA/issues/286
Only seen on firefox Mac 10.14 so far.  It seems that sometimes, when a line or equation is "hidden" behind another, it can be seen somewhat.  Very minor.  This was first noticed with the green text of the y=x line behind the active line seen here (rtl not needed).  Also seen in the game when a green line is layered over a black line.
![pastedimage](https://user-images.githubusercontent.com/41024075/52747845-0fee6580-2fa2-11e9-8175-0ae38a5da59c.png)

**Comment by pixelzoom** [comment] 2019-02-13 22:29
My best guess is that Firefox text anti-aliasing has translucent pixels around the edges, which would cause what is behind it to show through.  @jonathanolson does that sound plausible, or do you an explanation?  

In any case, my recommendation is to ignore this.  If anything, it's kind of nice, because it cues you to the fact that there's more than one line/equation in the same location.

**Comment by pixelzoom** [comment] 2019-02-13 22:31
@KatieWoe clarification about the title of this issue, which is "Firefox may have different line sizes".   This doesn't seem to have anything to do with line, it's the equation on the line.  Is that true, or am I missing something subtle in the screenshot above?

**Comment by KatieWoe** [comment] 2019-02-13 22:33
I meant line as in both the lines and the lines that make up text.

**Comment by pixelzoom** [comment] 2019-02-13 22:36
Ah yes, much more difficult to see (for me) with the line.  Below is a screenshot using Digital Color Meter to zoom in on the line.   This still looks like a symptom of how Firefox does anti-aliasing.

<img width="479" alt="screenshot_1054" src="https://user-images.githubusercontent.com/3046552/52748914-031f4100-2fa5-11e9-92cf-94d8b9911278.png">

**Comment by KatieWoe** [comment] 2019-02-13 22:37
I honestly only noticed that the line looked a bit more fuzzy, not the color.

**Comment by pixelzoom** [comment] 2019-02-13 22:49
There's a little bit of this in every browser that I've looked at.  For example:

macOS + Chrome with `y = x` off:

<img width="427" alt="screenshot_1057" src="https://user-images.githubusercontent.com/3046552/52749594-e257eb00-2fa6-11e9-9dcc-1067bc2927ee.png">

macOS + Chrome with `y = x` on:

<img width="442" alt="screenshot_1058" src="https://user-images.githubusercontent.com/3046552/52749606-ea178f80-2fa6-11e9-90ee-d7bb94d6ffe9.png">

When `y = x` is on, you can clearly see some green in the 'y' shown in Digital Color Meter.

**Comment by KatieWoe** [comment] 2019-02-13 22:53
Overall, I would agree that this doesn't need anything done.  Just documenting.

**Comment by pixelzoom** [comment] 2019-02-13 22:55
I talked with @jonathanolson about this on Slack.   It's definitely anti-aliasing.  It's probably more pronounced on Firefox because they're using a different rendering engine.  Using a different scenery `renderer` option for lines and equations might change the behavior, But I'd have to investigate, and that doesn't seem like time well-spent, because this issue is a (very minor) cosmetic blemish and causes no usability issues.  So I'm recommending that we close this as "won't fix".  

@amanda-phet your opinion?

**Comment by amanda-phet** [comment] 2019-02-14 05:00
I agree that it's almost a benefit, as @pixelzoom says, because it indicates that there are two layered equations/lines. Thank you for diving into the cause, and since it is an anti-aliasing issue and not something else (like the other string issues I was watching) I am happy to leave it as-is.

**Comment by pixelzoom** [comment] 2019-02-14 16:05
@KatieWoe thanks again for reporting. 

Closing.

**Closed by pixelzoom** 2019-02-14 16:05 UTC
Labels: type:wontfix
