### ISSUE TITLE
Slope indicators go off the screen when in the game screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-lines#122] opened 2019-02-11 17:42 UTC
For https://github.com/phetsims/QA/issues/277 and https://github.com/phetsims/QA/issues/278.  This does occur in the published version.
It is possible to make the blue slope markers go off the screen when in the game screen.
To do this, find a level where you make a line with the spinners and ideally can control both height and slope.  This can be done without control of both as long as the one not being controlled starts with a correct value for the bug.  Make sure the y-value of the point is as high as you can make it, then increase the y-value of the slope.  the slope need to be positive.
![graphing slope-intercept screenshot](https://user-images.githubusercontent.com/41024075/52582124-b17e8700-2de9-11e9-8c26-b9d9feb7d089.png)

**Comment by pixelzoom** [comment] 2019-02-11 18:11
Here's another more extreme example with `?showAnswers`, where the slope indicator really is outside the layoutBounds.

<img width="764" alt="screenshot_1036" src="https://user-images.githubusercontent.com/3046552/52583795-b9402a80-2ded-11e9-9cf9-5156bda80946.png">

**Comment by pixelzoom** [comment] 2019-02-11 18:13
In order to keep the slope indicator inside the layoutBounds (and on the graph), I'd need to invert it.   And in the 2 examples above, that would look like -4,-2 and -10,-10 respectively, which are not the rise and run values that the user has entered.  So whether we view this as a "teachable moment" or a limitation of the sim, I don't think it's something we should change.

@amanda-phet do you agree?

**Comment by amanda-phet** [comment] 2019-02-11 18:14
Wow! That is super easy to reproduce. What can we possibly do here? I will think about it.

**Comment by amanda-phet** [comment] 2019-02-11 18:17
@pixelzoom you think we should not change it? Or did I misread what you said? I like your suggestion to invert it, since that is what we would probably do with pencil and paper. But since it's been around for a while I wonder if was actually a known issue and we decided to leave it. It does have a familiar ring to it. 

I think it would be good to check with @ariel-phet since he has a better understanding of timelines than I do, and he was also the original designer of the GL sim.

**Comment by pixelzoom** [comment] 2019-02-11 18:19
We generally don't like to have things go off screen.  But in this case, I'm wondering why we'd want to do change anything.  The current behavior accurately depicts the slope that the user has entered, and shows them that what they entered is "off screen" in perhaps the clearest way possible.

**Comment by pixelzoom** [comment] 2019-02-11 18:21
@amanda-phet asked:
> @pixelzoom you think we should not change it? Or did I misread what you said? I like your suggestion to invert it, since that is what we would probably do with pencil and paper. ...

I didn't suggest inverting, I pointed out the problems with inverting.  So no, I don't think we should change anything, see https://github.com/phetsims/graphing-lines/issues/122#issuecomment-462436004.

**Comment by ariel-phet** [comment] 2019-02-11 22:56
@pixelzoom I think we should mark this as "won't fix"

The sim has been used extensively already in Java and HTML5, and we have not received any comments of this nature. Is it ideal to have things go off screen....not really, but I am not sure there is any particularly great solution that is worth the extra cost/complexity at this point.

**Comment by pixelzoom** [comment] 2019-02-12 00:04
OK, closing this as "won't fix". 

@KatieWoe thank you again for reporting.

**Closed by pixelzoom** 2019-02-12 00:04 UTC
Labels: design:general
