### ISSUE TITLE
Active line label overlaps with y=x, y=-x lines in long and rtl string tests

### ISSUE THREAD

**Issue by rea-laura** [phetsims/graphing-lines#120] opened 2019-02-07 20:57 UTC
<b>Test Device</b>

Leibniz

<b>Operating System</b>

iOS 12.1.3

<b>Browser</b>

Safari 12.1.3

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/277:
When y=x or y=-x lines are activated and the interactive line is overlaid over these green lines, the labels overlap, but only on some string tests.

<b>Steps to Reproduce</b>

1) go to sim with either long or rtl string test query parameter
2) go to slope-intercept or point-slope screen (2 and 3rd panels on startup)
3) check the y=x or y=-x box
4) position the movable line on top of a green line
5) note that the line label overlaps with the green line label. Only happens when string test is long or rtl. Otherwise the green label is replaced with the black label and no overlap occurs. 

<b>Visuals</b>

Overlap (rtl and long): 
![3746ba0d-6af1-4e39-810e-e5586f2cfca6](https://user-images.githubusercontent.com/44005544/52442202-ca342780-2adf-11e9-8863-ca832a038742.png)

![e1771936-af3d-44f0-b295-b371f225675a](https://user-images.githubusercontent.com/44005544/52442220-d61fe980-2adf-11e9-912f-4c459739cb3e.png)

No overlap (no string test, double, and X):
![eef48432-7a43-4e80-97f2-f095feb66ab6](https://user-images.githubusercontent.com/44005544/52442246-e5069c00-2adf-11e9-85a9-3ed3008c2c15.png)

![96779563-6214-4988-b388-6de1af1e7525](https://user-images.githubusercontent.com/44005544/52442262-ef289a80-2adf-11e9-893c-6e5e5aca3204.png)

![a292aa56-e3a3-41cf-adcd-a9e3cf87a9ca](https://user-images.githubusercontent.com/44005544/52442278-f51e7b80-2adf-11e9-9e69-373d1c316955.png)

**Comment by pixelzoom** [comment] 2019-02-07 21:52
Thanks @rea-laura, I'll investigate.

I was hoping that `?stringTest=double` would make it a little easier to see what's going on.  But that looks fine:

<img width="1415" alt="screenshot_1030" src="https://user-images.githubusercontent.com/3046552/52445206-ae348400-2ae7-11e9-9837-732235c741c9.png">

**Comment by pixelzoom** [comment] 2019-02-07 22:35
I said:
> My WAG is that the equations have different `maxWidth` values ...

To test this...

In `LineFormsGraphNode`, I added this to the constructor:

```js
console.log( 'interactiveLineNode.equationNode.maxWidth=' + this.interactiveLineNode.equationNode.maxWidth );
```

And I modified `standardLineAdded` like so:

```js
    standardLineAdded: function( line ) {
      var lineNode = new LineNode( new Property( line ), this.model.graph, this.model.modelViewTransform,
        { equationType: this.equationType } );
      console.log( 'standardLineAdded: line=' + line.toString() + ', lineNode.equationNode.maxWidth=' + lineNode.equationNode.maxWidth );
      this.standardLinesParentNode.addChild( lineNode );
    },
```

Start the sim, go to Slope-Intercept screen, 'y = x' checkbox checked.  Console output is:

```
interactiveLineNode.equationNode.maxWidth=200
interactiveLineNode.equationNode.maxWidth=200
interactiveLineNode.equationNode.maxWidth=200
standardLineAdded: line=Line[x1=0 y1=0 x2=1 y2=1 rise=1 run=1 color=rgb( 16, 178, 15 )], lineNode.equationNode.maxWidth=200
```

So `maxWidth` is the same (200) for the equations on the interactive line and y=x.

**Comment by pixelzoom** [comment] 2019-02-07 23:01
Odd...  If I move the interactive line from y=x, to y=0, then back to y=x, the problem (permanently!) goes away.   The interactive equation then perfectly overlaps y=x (and y=-x).

**Comment by pixelzoom** [comment] 2019-02-07 23:30
My WAG in the preceding comment was correct.  So this was easily fixed by fully resetting the location of all equation subcomponents (Nodes) whenever the equation updates, see commit above. 

A potential risk of this fix is that some equation was relying on the location of a previous update, and some part of the equation would be in the wrong location.  I looked carefully at equations in Slope-Intercept, Point-Slope and Line Game screens (because this same code is used in Line Game), and I didn't see any issues. 

@rea-laura back to you to verify in master.  If all looks OK, please leave the issue open for regression testing in 1.3.0-rc.2.

**Comment by KatieWoe** [comment] 2019-02-08 19:46
To me this looks like the same issue as https://github.com/phetsims/graphing-lines/issues/114, as that only occurred with longer strings.

**Comment by pixelzoom** [comment] 2019-02-08 22:20
@KatieWoe it's actually a subtly different issue.

**Comment by pixelzoom** [comment] 2019-02-08 22:37
To verify this issue:

1. Start the sim with normal strings (no stringTest query parameter)
2. Go to Slope-Intercept screen
3. Select check boxes for y=x and y=-x.
4. Move the interactive line to y=x and verify that the equation on the interactive (black) line exactly covers the equations on the y=x (green) line.
5. Repeat step 4 for y=-x.
6. Go to Point-Slope screen.
7. Repeat steps 3-5 
8. Re-starting the sim with `?stringTest=long` and repeat steps 1-7.

**Comment by pixelzoom** [comment] 2019-02-08 22:44
You could also do the above verification steps 1-7 for a RTL language, but `stringTest=long` is essentially testing the same code path.

**Comment by KatieWoe** [comment] 2019-02-08 22:47
Looks good on master.

**Comment by pixelzoom** [comment] 2019-02-09 02:15
Pending regression testing in 1.3.0-rc.2.

**Comment by KatieWoe** [comment] 2019-02-12 23:21
This seems to be occurring again.
![regress](https://user-images.githubusercontent.com/41024075/52674905-4795d880-2ee2-11e9-92e2-47194d359b81.jpg)

**Comment by pixelzoom** [comment] 2019-02-12 23:44
My apologies, the fix in https://github.com/phetsims/graphing-lines/commit/547817249e60e3aad415fd4c02cdd7875edd8934 did not get cherry-picked into the 1.3 branch, so it's not in 1.3.0-rc.2. Please skip this we'll come back to it in a quick 1.3.0-rc.3.

**Comment by pixelzoom** [comment] 2019-02-13 00:37
To verify this issue, follow the steps in https://github.com/phetsims/graphing-lines/issues/120#issuecomment-461971005.

**Comment by KatieWoe** [comment] 2019-02-13 19:22
Fixed in both rcs

**Closed by KatieWoe** 2019-02-13 19:22 UTC
Labels: status:fixed-pending-testing, type:bug
