### ISSUE TITLE
some saved lines cannot be erased

### ISSUE THREAD

**Issue by BryceAG** [phetsims/graphing-lines#54] opened 2015-11-19 23:51 UTC
Test device:
Bates, Turing

Operating System:
Windows 7 64-bit, OS X 10.9.5

Browser:
FIrefox 42.0, IE 11.0.9600.17843, Chrome 46.0.2490.86 m, Safari 9.0(9537.86.1.56.2)

Problem description:
If a specific line is saved in point slope, it will not disappear when reset or when erase line is pressed. I have tried multiple lines, but it appears to be just this line. The screenshot will show which line it is.

Steps to reproduce:
In point slope, save a line with the purple and blue dots placed where they are in the screenshot (they can be in the reverse position). It will not disappear if the reset or erase line button is pressed.

Severity:

Screenshots:
The line that was made:
![capture](https://cloud.githubusercontent.com/assets/15327201/11287720/1edff970-8edb-11e5-8ca6-6175b4af7318.PNG)

The line doesn't disappear (erase button still grayed out):
![capture2](https://cloud.githubusercontent.com/assets/15327201/11287747/4d665622-8edb-11e5-857a-8ee26cc653da.PNG)

also note that issue #53 is visible in screenshots

Troubleshooting information (do not edit):
  
Name: ‪Graphing Lines‬

URL: http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.1.0-rc.1/graphing-lines_en.html

Version: 1.1.0-rc.1 2015-11-16 20:17:53 UTC

Features missing: touch, fullscreen

Flags: pointerEnabled, msPointerEnabled

User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; InfoPath.3; BRI/2; rv:11.0) like Gecko

Language: en-US

Window: 1366x643

Pixel Ratio: 1/1

WebGL: WebGL 0.94

GLSL: WebGL GLSL ES 0.94

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 16384x16384

OES_texture_float: true

Dependencies JSON: {"assert":{"sha":"3921bc37","branch":"master"},"axon":{"sha":"fffc6c30","branch":"master"},"babel":{"sha":"288260a1","branch":"master"},"brand":{"sha":"3b236d6f","branch":"master"},"chipper":{"sha":"6735d265","branch":"master"},"dot":{"sha":"5c39b7d8","branch":"master"},"graphing-lines":{"sha":"6e531507","branch":"1.1"},"joist":{"sha":"2a5b44c4","branch":"master"},"kite":{"sha":"84e84bca","branch":"master"},"phet-core":{"sha":"73a034c6","branch":"master"},"phetcommon":{"sha":"61a7c5fa","branch":"master"},"scenery":{"sha":"c0c08ec5","branch":"master"},"scenery-phet":{"sha":"61d8e7ed","branch":"master"},"sherpa":{"sha":"be8c4fc9","branch":"master"},"sun":{"sha":"8d290320","branch":"master"},"tandem":{"sha":"e98bd8c3","branch":"master"},"vegas":{"sha":"03114c7c","branch":"master"},"vibe":{"sha":"40a28182","branch":"master"}}

**Comment by orejolaphet** [comment] 2015-11-20 16:51
Also present in OS X 10.11.0 Safari 9.0 (11601.1.56)

**Comment by pixelzoom** [comment] 2015-11-20 18:14
Reproduced, not platform specific. Really weird, doesn't occur for all lines. "Reset All" does not erase the saved lines either.

**Comment by pixelzoom** [comment] 2015-11-20 18:19
I can only reproduce this when the slope is an integer multiple of `-(7/9)`. Eg, `-7/9`, `7/-9`, `-14/18`, `14/-18`. Bizarre.

**Comment by pixelzoom** [comment] 2015-11-20 18:21
Not specific to the "Point Slope" screen, occurs in other screens when using similar slope values.

**Comment by pixelzoom** [comment] 2015-11-20 18:25
Reproduced, not platform specific. Additional notes:

• Not platform specific.
• Not screen specific; reproducing on other screens.
• Only occurs when the slope is an integer multiple of `-(7/9)`. Eg, `-7/9`, `7/-9`, `-14/18`, `14/-18`. 
• "Reset All" does not erase the problem lines either.
• Other saved lines continue to be saved/erased/reset correctly.

**Comment by pixelzoom** [comment] 2015-11-25 17:09
Related to https://github.com/phetsims/tasks/issues/374.

**Comment by pixelzoom** [comment] 2015-11-29 01:43
Saved lines are stored in `LineFormsModel.savedLines`, which is of type `{ObservableArray.<Line>}`. I have a hunch that this will turn out to be a bug in ObservableArray.

**Comment by pixelzoom** [comment] 2015-11-29 02:22
No problem found with ObservableArray.  This is a precision problem with determining whether 2 lines are the same. That algorithm returns true of 2 points are on both lines.  Here's the function (in `Line`) used to check whether a point is on a line:

```js
    onLineXY: function( x, y ) {
     ...
        return ( x === this.solveX( y ) );
    ...
    },
```

For example with `Line[x1=1 y1=-3 x2=-6 y2=6 rise=9 run=-7 color=rgb( 160, 160, 160 )]`, the call to `solveX` returns -5.999999999999999 when it should return -6.

Rather than muck around with this in the model, it would be better to keep a map between model elements (Line) and their corresponding Nodes, instead of iterating over the Nodes to find one whose corresponding Line is "the same".

**Comment by pixelzoom** [comment] 2015-11-29 02:32
Since ES5 lacks a Map data type, a less invasive fix is to use referential equality to remove lines. 

In LineFormsGraphNode, change this:

```js
    // @private Removes the node that corresponds to the specified line.
    removeLineNode: function( line, parentNode ) {
      for ( var i = 0; i < parentNode.getChildrenCount(); i++ ) {
        var node = parentNode.getChildAt( i );
        if ( line.same( node.lineProperty.get() ) ) {
          parentNode.removeChild( node );
        }
      }
    }
```

to this:

```js
    // @private Removes the node that corresponds to the specified line.
    removeLineNode: function( line, parentNode ) {
      var removed = false;
      for ( var i = 0; i < parentNode.getChildrenCount() && !removed; i++ ) {
        var node = parentNode.getChildAt( i );
        if ( line === node.lineProperty.get() ) {
          parentNode.removeChild( node );
          removed = true;
        }
      }
      assert && assert( removed, 'no Node found for line ' + line.toString() );
    }
```

So we're replacing the `line.same(...)` test with `line === ...`.  And note the added assertion to verify that a Node is actually found and removed.

**Comment by pixelzoom** [comment] 2015-11-29 02:43
Fix applied in master and 1.1 branch.  Here's a dev version built off of the 1.1 branch:

http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.1.0-dev.5/graphing-lines_en.html

@BryceAG please verify that this is fixed. If it checks out OK, this issue may be closed. (And good catch!)

**Comment by pixelzoom** [comment] 2015-11-29 03:16
@BryceAG Actually... after verifying, don't close this issue, please assign it back to me. I need to check whether this same issue can manifest itself in the Game, or other places where `Line.same` is used.

**Comment by pixelzoom** [comment] 2015-11-30 23:34
The floating point errors in `Line` functions do present some problems in the Game. Tracking that issue in  #56.

**Comment by pixelzoom** [comment] 2015-12-03 20:20
I'm going to close this. It will be verified by spot testing a new RC version, in conjunction with #56 and other issues specific to 1.1.0-rc.1.

**Closed by pixelzoom** 2015-12-03 20:20 UTC

**Comment by BryceAG** [comment] 2015-12-03 21:16
Sorry for the delay in testing. It does look like it is fixed in the new dev version.

**Comment by pixelzoom** [comment] 2015-12-04 02:33
Thanks @BryceAG.
